# This secret store PostgreSQL credentials, both user and password are encoded using base64
# To convert  strings to base64 do as follows:
# echo -n 'admin' | base64

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: django-realworld-ns
type: Opaque
data:
  user: cm9vdA==
  password: UGFzc3cwcmQ=