# This job creates a pod which runs the Django migration.

apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
  namespace: django-realworld-ns
spec:
  template:
    spec:
      containers:
        - name: migrations-container
          image: abensalah/django-realworld-example-app:postgres
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service
      restartPolicy: Never
  backoffLimit: 3